In [11]:
import numpy as np
tempratures = np.array([32.5,34.2,36.8,29.3 , 31.0 , 38.7 , 23.1 , 18.5 , 22.8 , 37.2])
day = np.where(tempratures > 35)
arr = np.array(day)
print(*(arr+1))
for i in tempratures :
    if i > 35:
        print("hot day",i)
    elif i < 5:
        print("cold day",i)

[ 3  6 10]
hot day 36.8
hot day 38.7
hot day 37.2


In [23]:
monthy_sales = np.array([12,135,140,165,180,155,168,190,205,198,210,225])
split_1 = np.split(monthy_sales , 4)
index = np.where(split_1)
index = np.array(index)
count = 0
for i in split_1:
    print("Quarter",count+1,"sales")
    count += 1
    print(i)
    
    

Quarter 1 sales
[ 12 135 140]
Quarter 2 sales
[165 180 155]
Quarter 3 sales
[168 190 205]
Quarter 4 sales
[198 210 225]


In [33]:
customer_ids = np.array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])
last_purchase_days_ago = np.array([5, 15, 20, 25, 30, 35, 40, 45, 50, 55])
last_days_less_30 = np.where(last_purchase_days_ago <= 30)[0]
# last_days_less_30 = np.array(last_days_less_30)
# print(last_days_less_30+1)
last_days_more_30 = np.where(last_purchase_days_ago > 30)[0]
# last_days_more_30 = np.array(last_days_more_30)
# print(last_days_more_30+1)
# count = 0
for i in last_days_less_30:
    print(customer_ids[i],end=",")
print()
for i in last_days_more_30:
    print(customer_ids[i],end=",")

# for i in last_days_less_30:
#     if customer_ids[count] == i:
#         print(customer_ids[count])
#         count += 1
#     else:
#         count += 1

101,102,103,104,105,
106,107,108,109,110,

In [50]:
# Employee data for full-time employees
full_time_employees = np.array([
[101, 'John Doe', 'Full-Time', 55000],
[102, 'Jane Smith', 'Full-Time', 60000],
[103, 'Mike Johnson', 'Full-Time', 52000]
])
# Employee data for part-time employees
part_time_employees = np.array([
[201, 'Alice Brown', 'Part-Time', 25000],
[202, 'Bob Wilson', 'Part-Time', 28000],
[203, 'Emily Davis', 'Part-Time', 22000]
])

# print(np.vstack((full_time_employees,part_time_employees)))
new = np.vstack((full_time_employees,part_time_employees))
for i in new:
    print("Employee ID : ",i[0],"Name : ",i[1] , "Type : ",i[2],"Salary : ",i[3])

Employee ID :  101 Name :  John Doe Type :  Full-Time Salary :  55000
Employee ID :  102 Name :  Jane Smith Type :  Full-Time Salary :  60000
Employee ID :  103 Name :  Mike Johnson Type :  Full-Time Salary :  52000
Employee ID :  201 Name :  Alice Brown Type :  Part-Time Salary :  25000
Employee ID :  202 Name :  Bob Wilson Type :  Part-Time Salary :  28000
Employee ID :  203 Name :  Emily Davis Type :  Part-Time Salary :  22000


In [56]:
list = [
np.array([3, 2, 8, 9]),
np.array([4, 12, 34, 25, 78]),
np.array([23, 12, 67])
]
count = 0
for i in list:
    print(np.mean(list[count]) , end=",")
    count += 1
    


5.5,30.6,34.0,

In [64]:
x_odd = np.array([1, 2, 3, 4, 5, 6, 7])
print("Printing the Original array : ")
print(x_odd)
print("Median of the array that contains odd no. of elements:\n",np.median(x_odd))

Printing the Original array : 
[1 2 3 4 5 6 7]
Median of the array that contains odd no. of elements:
 4.0


In [71]:
arr = [20, 2, 7, 1, 34]
ar_1 = np.array(arr,dtype=')
stddd = (np.std(arr))
print(stddd)

12.576167937809991
